services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - doc-store
    environment:
      QDRANT_HOST: doc-store
      QDRANT_PORT: 6333
    ports:
      - "8000:80"
    networks:
      - backend

  doc-store:
    image: qdrant/qdrant
    container_name: doc-store
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - backend

volumes:
  qdrant_data:

networks:
  backend:
